# Array Birleştirme

In [5]:
import numpy as np

### Tek Boyut

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [7]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [9]:
z=np.array([7,8,9])

In [10]:
np.concatenate([a,b,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### İki Boyut

In [13]:
a=np.array([[1,2,3],
            [4,5,6]])

In [14]:
# # satır bazında, alt alta olacak şekilde yerleştirir.
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- axis, eksen belirtmek için kullanılır.
- 0(sıfır) satırları; 1(bir) sütunları

In [15]:
# yan yana olacak şekilde sütun bazında bir birleştirme gerçekleştirildi.
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])