# NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [4]:
np.array([3.14, 4, 2, 13]) 
# sabit tip olduğu için bütün sayıları ondalıklı bir tipe çevirir.

array([ 3.14,  4.  ,  2.  , 13.  ])

In [5]:
np.array([3.14, 4, 2, 13], dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [6]:
np.array([3.14, 4, 2, 13], dtype="int")

array([ 3,  4,  2, 13])