# Fancy Index ile Elemanlara Erişmek

In [1]:
import numpy as np

In [2]:
v=np.arange(0,30,3)

In [3]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
v[1]

3

In [5]:
[v[1],v[3],v[5]]

[3, 9, 15]

- listeyi, NumPy array'ine index olarak verebiliriz

## Tek Boyutta Fancy

In [6]:
al_getir=[1,3,5]

In [7]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
v[al_getir]

array([ 3,  9, 15])

## İki Boyutta Fancy

In [9]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
satir=np.array([0,1]) # 0. satır, 1. sütun -> 1 var
sutun=np.array([1,2]) # 1. satır, 2. sütun -> 5 var

In [11]:
m[satir, sutun]

array([1, 5])

## Basit index ile fancy index

In [15]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
m[0]

array([0, 1, 2])

In [13]:
m[1,2]

5

In [14]:
m[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [16]:
m[0,[1,2]]

array([1, 2])

## Slice ile fancy

In [17]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])