# Index ile Elemanlara Erişmek

In [1]:
import numpy as np

In [6]:
# 3 satırlı, 2 sütun
b=np.random.randint(10,size=(3,3,2))
b

array([[[3, 7],
        [9, 3],
        [1, 7]],

       [[0, 0],
        [9, 9],
        [1, 5]],

       [[9, 2],
        [1, 4],
        [3, 9]]])

In [4]:
b.shape

(3, 3, 2)

In [5]:
b.ndim

3

In [7]:
b.size

18

### Tek Boyutlu

In [2]:
a=np.random.randint(10,size=10)
a

array([0, 2, 0, 9, 4, 1, 0, 1, 4, 9])

In [8]:
a[0]

0

In [9]:
a[-1]

9

In [10]:
a[0]=7

In [11]:
a

array([7, 2, 0, 9, 4, 1, 0, 1, 4, 9])

### İki Boyutlu

In [22]:
t=np.random.randint(10, size=(2,3,4))
m

array([[[7, 9, 7, 0],
        [9, 3, 9, 3],
        [0, 4, 5, 5]],

       [[1, 1, 9, 2],
        [5, 1, 9, 9],
        [9, 6, 4, 3]]])

In [17]:
t[0]

array([[5, 1, 6, 9],
       [7, 0, 7, 5],
       [3, 1, 5, 6]])

In [18]:
t[1]

array([[4, 7, 6, 9],
       [4, 3, 4, 4],
       [8, 9, 8, 0]])

In [19]:
e1,e2=np.random.randint(10, size=(2,3,4))

In [20]:
e1

array([[6, 5, 2, 9],
       [1, 8, 4, 9],
       [8, 2, 1, 1]])

In [21]:
e2

array([[1, 9, 6, 1],
       [1, 4, 4, 3],
       [2, 2, 8, 2]])

In [23]:
m=np.random.randint(10,size=(3,4))

In [24]:
m

array([[4, 1, 8, 0],
       [3, 8, 0, 4],
       [7, 5, 8, 3]])

In [25]:
m[0,0] # 0. satır, 0. sütun

4

In [26]:
m[0,1] # 0. satır, 1.sütun

1

In [27]:
m[1,1]

8

In [28]:
m[2,3]=56

In [29]:
m

array([[ 4,  1,  8,  0],
       [ 3,  8,  0,  4],
       [ 7,  5,  8, 56]])

In [30]:
# sabit tipli olduğundan float bir değer eklediğimizde
m[0,2]=9.5

In [31]:
m # 9.5 olan float sayıyı int'e çevirdi: 9

array([[ 4,  1,  9,  0],
       [ 3,  8,  0,  4],
       [ 7,  5,  8, 56]])

oluşturma esnasında içerisinde sadece 1 tane ondalıklı değer varsa bütün array'in tipini ondalıklı olarak görür. fakat var olan bir array'e dışarıdan array dışı farklı bir tip ile ekleme yapmaya çalıştığımızda var olan tipini korur