# Matemetiksel İşlemler

In [1]:
import numpy as np

In [2]:
v=np.array([1,2,3,4,5])

In [3]:
v-1

array([0, 1, 2, 3, 4])

In [4]:
v*5

array([ 5, 10, 15, 20, 25])

In [5]:
v/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
v*4

array([ 4,  8, 12, 16, 20])

In [7]:
v*4-3

array([ 1,  5,  9, 13, 17])

In [8]:
(v*4-3)/3

array([0.33333333, 1.66666667, 3.        , 4.33333333, 5.66666667])

In [9]:
v**2

array([ 1,  4,  9, 16, 25])

In [10]:
v**3

array([  1,   8,  27,  64, 125])

In [11]:
# kalan
v%2

array([1, 0, 1, 0, 1])

# ufunc

In [12]:
# çıkarma işlemi
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [13]:
# toplama işlemi
np.add(v,1)

array([2, 3, 4, 5, 6])

In [14]:
# çarpma işlemi
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [15]:
# bölme işlemi
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [16]:
# kuvvetini alma
np.power(v,3)

array([  1,   8,  27,  64, 125])

In [17]:
# kalan bulma
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [18]:
# mutlak değer
np.absolute(np.array([-3,-4,5,-6]))

array([3, 4, 5, 6])

In [19]:
# trigonometri işlemleri
np.sin(360)

0.9589157234143065

In [20]:
# trigonometri işlemleri
np.cos(180)

-0.5984600690578581

In [21]:
# logaritmik işlemler
v=np.array([1,2,3])
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [22]:
# logaritmik işlemler - derece
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [23]:
# logaritmik işlemler - derece
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [24]:
# dökümanlar - NumPy'ın ana dökümantasyonu
?np

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

In [25]:
# cheat sheet - kopya kağıdı

# İstatistiksel Hesaplamalar

In [26]:
v

array([1, 2, 3])

In [27]:
np.mean(v,axis=0)

2.0

In [28]:
m=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [29]:
np.mean(m,axis=0) # (1+1+1)/3=1, (2+2+2)/3=2...

array([1., 2., 3., 4., 5.])

In [30]:
np.mean(m,axis=1) # (1+2+3+4+5)/5=3, (1+2+3+4+5)/5=3...

array([3., 3., 3.])

In [31]:
v.sum()

6

In [32]:
v.min()

1