# Sıfırdan Array Oluşturma

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5)) # 3 satır, 5 sütun

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [7]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [8]:
# 0'dan 30'a kadar (30 dahil değil) 3'er 3'er artacak şekilde doğrusal bir dizi oluşturduk
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
type(np.arange(0,30,3))

numpy.ndarray

In [10]:
# 0 ile 1 arasında 10 tane değer oluştur
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
# oluşturmak istediğim sayılar belirli bir dağılım yapısına uygun olsun
# istatistik teorisindeki normal dağılıma uygun olsun
# verdiğimiz standart sapmaya ve ortalamaya bağlı olarak veriler üretilsin

# ortalama 10, standart sapma 4, satır 3, sütun 4
np.random.normal(10,4,(3,4))
# 2 boyutlu array, matris

array([[ 9.51668171, 11.22745464, 10.08783349,  7.53074101],
       [ 7.33806572,  7.74476118, 11.72813934, 13.88245585],
       [14.65663092,  4.83838101, 11.58130793, 16.50334837]])

In [12]:
np.random.normal(10,4,5)

array([ 5.36659305, 13.86971492,  2.65947933,  8.65471107, 13.67611035])

In [13]:
# tek boyutlu array'in karşılığı vektördür
# iki boyutlu array'in karşılığı matristir

In [14]:
# int değerlerden rastgele oluşturalım.
np.random.randint(0,10,(3,3)) # 10 dahil değildir

array([[3, 0, 6],
       [8, 5, 0],
       [2, 6, 8]])

In [15]:
np.random.randint(10,size=(3,2,2))

array([[[8, 0],
        [9, 4]],

       [[4, 6],
        [2, 2]],

       [[3, 3],
        [0, 1]]])

In [16]:
# 3 satırlı, 2 sütun
np.random.randint(10,size=(3,3,2))

array([[[7, 4],
        [9, 8],
        [7, 1]],

       [[5, 0],
        [5, 5],
        [2, 9]],

       [[1, 4],
        [2, 7],
        [8, 4]]])

In [17]:
np.random.randint(10,size=(3,2,2)).ndim

3