# Yeniden Şekillendirme

In [4]:
import numpy as np

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# tek boyutlu -> çok boyutlu
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.ndim # tek boyutlu array -> vektör

1

In [11]:
# iki boyutlu array -> matris
b=a.reshape((1,9)) # 1 satır, 9 sütun
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
b.ndim # iki boyutlu

2