# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,size=(5,5))

In [3]:
a

array([[9, 4, 3, 4, 3],
       [3, 2, 1, 5, 5],
       [7, 1, 5, 7, 1],
       [0, 6, 7, 3, 7],
       [9, 3, 6, 8, 3]])

In [4]:
alt_a = a[0:3,0:2]
alt_a

array([[9, 4],
       [3, 2],
       [7, 1]])

In [5]:
alt_a[0,0]=99999
alt_a[1,1]=777

In [6]:
alt_a

array([[99999,     4],
       [    3,   777],
       [    7,     1]])

In [7]:
a

array([[99999,     4,     3,     4,     3],
       [    3,   777,     1,     5,     5],
       [    7,     1,     5,     7,     1],
       [    0,     6,     7,     3,     7],
       [    9,     3,     6,     8,     3]])

- alt küme içerisinde yaptığımız değişikliğin ana array içerisinde değişikliğe neden olmaması için

In [8]:
m=np.random.randint(10, size=(5,5))
m

array([[1, 7, 4, 3, 8],
       [1, 2, 8, 2, 1],
       [2, 1, 2, 1, 8],
       [1, 0, 8, 7, 1],
       [7, 3, 6, 3, 6]])

- copy() metodunu array'in sonuna bağladığımızda seçmiş olduğu alt kümeyi, ana array'den bağımsızlaştırıyor.

In [9]:
alt_b=m[0:3,0:2].copy()
alt_b

array([[1, 7],
       [1, 2],
       [2, 1]])

In [10]:
alt_b[0,0]=9999

- oluşturduğumuz ilk array'in yapısında hiçbir bozukluk meydana gelmedi. fakat seçmiş olduğumuz alt küme üzerinde değişiklik yapmış olduk.

In [11]:
alt_b

array([[9999,    7],
       [   1,    2],
       [   2,    1]])

In [12]:
alt_b*3

array([[29997,    21],
       [    3,     6],
       [    6,     3]])

In [13]:
alt_b

array([[9999,    7],
       [   1,    2],
       [   2,    1]])

In [14]:
m

array([[1, 7, 4, 3, 8],
       [1, 2, 8, 2, 1],
       [2, 1, 2, 1, 8],
       [1, 0, 8, 7, 1],
       [7, 3, 6, 3, 6]])

In [15]:
m=np.random.randint(10,size=(3,5))
m

array([[9, 1, 5, 2, 3],
       [6, 3, 9, 0, 6],
       [1, 0, 6, 8, 9]])

In [16]:
m[0:1]

array([[9, 1, 5, 2, 3]])

In [17]:
m[0:1].shape

(1, 5)

In [18]:
m[0:1].ndim

2

In [19]:
m[:,2]

array([5, 9, 6])

In [20]:
m[:2,:3]

array([[9, 1, 5],
       [6, 3, 9]])

In [21]:
[m[1],m[2]]

[array([6, 3, 9, 0, 6]), array([1, 0, 6, 8, 9])]

In [22]:
v=np.array([0,3,6,9,12,15,18,21,24,27])

In [23]:
v[[1,2,3]]

array([3, 6, 9])

In [25]:
m

array([[9, 1, 5, 2, 3],
       [6, 3, 9, 0, 6],
       [1, 0, 6, 8, 9]])

In [24]:
m[[1,2]]

array([[6, 3, 9, 0, 6],
       [1, 0, 6, 8, 9]])

In [26]:
m[0,[1,2]] # 0. satırın 1 ve 2. indexdeki değerleri

array([1, 5])

In [27]:
m[0:,[1,2]]

array([[1, 5],
       [3, 9],
       [0, 6]])